### PR TITLE
add additional config to fpm lwrp

### PR DESCRIPTION
**Pull request by willejs**
Added an attribute to the fpm_pool LWRP to add additional config to the fpm pool config.

### CODE REVIEW

**Comment by Rockstar04** [comment]
Looks like a solid imporvement! Thanks @willejs 

I will do my best to get at new release (1.7.0) out by the end of the week

**Comment by willejs** [comment]
Cheers, I may make a few more PRs as i move this towards production. We have been using priest-jim's fork, which was better in some ways.

**Comment by Vincentv92** [comment]
How can I use this properly?

`php_fpm_pool "default" do
  additional_config = {
    'php_admin_value[upload_max_filesize]' => '20M',
    'test' => 'is not present in pool config'
  }
  action :install
end`

Won't sadly work, is there something wrong with my recipe?

**Comment by willejs** [comment]
@Vincentv92 are you using the correct cookbook version?

**Comment by ThatGerber** [comment]
@Vincentv92 Resource properties are methods not attributes. Since it's being passed as a hash, as well, you won't need curly brackets (in newer Ruby).

```
php_fpm_pool "default" do
  additional_config(
    'php_admin_value[upload_max_filesize]': '20M',
    'test': 'is not present in pool config'
  )
  action :install
end
```

**Comment by Vincentv92** [comment]
@ThatGerber Good to know I can use this syntax as well, in this notation it doesn't change a thing sadly
@willejs I did a fresh clone and installation (so I assume I use the latest version 1.9) is there a way of enforcing this in my recipe?

**Pull request merged**
