### PR TITLE
Adds php5enmod support for Ubuntu >12.04

### PR DESCRIPTION
**Pull request by estahn**
Fixes #107, #81

### CODE REVIEW

**Comment by estahn** [comment]
Any updates on this?

**Comment by walkah** [comment]
It'd be nice to get a release out with this included. currently, all pear/pecl extensions are failing for me in ubuntu 14.04

**Comment by Rud5G** [comment]
@someara can you provide us with some info ?

**Comment by Rud5G** [comment]
@estahn the php5enmod & php5dismod are available since PHP 5.4+ on debian and ubuntu, perhaps an additional check if the version is high enough?

**Comment by Igorshp** [comment]
any progress on this? Would be great to this this functionality.
:+1:

**Comment by rahulpatil323** [comment]
+1
We need this.

**Comment by Rockstar04** [comment]
This seems straight forward enough, I will be at home with family over the holiday weekend, but I will spend an hour or two trying to get some of the many pull requests here merged and a new release taged for everyone.

**Comment by Rockstar04** [comment]
Everything in the kitchen looks good to me.

**Comment by Igorshp** [comment]
@estahn @Rockstar04 great, thanks!

**Pull request merged**
