### PR TITLE
Added ChefSpec matchers

### PR DESCRIPTION
**Pull request by yoshiwaan**
Following on from https://github.com/opscode-cookbooks/php/pull/128

Now points to master

### CODE REVIEW

**Comment by Igorshp** [comment]
awesome, thanks!

**Comment by Rockstar04** [comment]
Thanks @yoshiwaan !

**Comment by yoshiwaan** [comment]
No worries.

Is 1.6.0 going to be the rewrite or will that be 2.0.0?

**Comment by Rockstar04** [comment]
The 1.6.0 I am trying to get together will just be a collection of current pull requests to get the cookbok working again for people, Someara will be continuing on with the rewrite, which will most likely be 2.0.0 since it looks like it will break compatibility with current setups.

**Pull request merged**
