### PR TITLE
Added matchers library

### PR DESCRIPTION
**Pull request by yoshiwaan**
Chefspec good!
Matchers good!
Unit tests good!

What's not to like?

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @yoshiwaan

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by Igorshp** [comment]
awesome, did the chefspec matchers last night for our own project. Great to see someone done it here.
:+1:

**Comment by Rockstar04** [comment]
Aaaa, I didnt realize this was made against the develop branch. This will have to wait for that rewrite to finish up

**Comment by Igorshp** [comment]
@someara why was this closed? 

@Rockstar04 should this not simply be rebased against master branch?

**Comment by Rockstar04** [comment]
Sorry @Igorshp I didnt look into this deep enough to see if it applies to the current master since I am mostly worried about getting blocking issues for the cookbook resolved and get a new release tagged.

**Comment by Igorshp** [comment]
@Rockstar04 sure, but would you accept the PR if it was rebased against master?
I can quickly do that if @yoshiwaan is not around

**Comment by Rockstar04** [comment]
Sure, I see no harm in that

**Comment by yoshiwaan** [comment]
I'm around, and it definitely makes no sense to close this PR because it
points to develop!

In any case I have to make a new PR as you can't change the branch one
points to.

**Comment by yoshiwaan** [comment]
https://github.com/opscode-cookbooks/php/pull/136

**Pull request closed without merging**
